dist: trusty
git:
  depth: 1
language: node_js
sudo: required


before_install:
  - ./docker-util/sh/install-docker-on-trusty.sh
  - sudo service docker stop
  - sudo dockerd --experimental &
  - docker version

env:
  global:
    - DOCKER_IMAGE_NAME=travis-cli
    - DOCKER_ORGANIZATION=beeglercorp
    - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME
    - IMAGE_SIZE_THRESHOLD=35

install: true

stages:
  - name: Build
  - name: Test Pull
    if: branch = master AND type = pull

jobs:
  include:
    - stage: Build
      env: TAG=latest
      script:
        - docker build --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t $IMAGE_SIZE_THRESHOLD
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
            ./docker-util/sh/push-image.sh -i $DOCKER_IMAGE_NAME -n $DOCKER_PUBLIC_IMAGE_NAME -p $DOCKER_PASSWORD -t $TAG -u $DOCKER_USERNAME;
          fi
    - stage: Build
      env: TAG=alpine-edge
      script:
        - docker build --build-arg ALPINE_VERSION=edge --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t $IMAGE_SIZE_THRESHOLD
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
            ./docker-util/sh/push-image.sh -i $DOCKER_IMAGE_NAME -n $DOCKER_PUBLIC_IMAGE_NAME -p $DOCKER_PASSWORD -t $TAG -u $DOCKER_USERNAME;
          fi
    - stage: Build
      env: TAG=alpine-3.5
      script:
        - docker build --build-arg ALPINE_VERSION=3.5 --tag $DOCKER_IMAGE_NAME --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_IMAGE_NAME -t $IMAGE_SIZE_THRESHOLD
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
            ./docker-util/sh/push-image.sh -i $DOCKER_IMAGE_NAME -n $DOCKER_PUBLIC_IMAGE_NAME -p $DOCKER_PASSWORD -t $TAG -u $DOCKER_USERNAME;
          fi
    - stage: Test Pull
      env: TAG=latest
      script:
        - ./sh/ci/test.sh
    - stage: Test Pull
      env: TAG=alpine-edge
      script:
        - ./sh/ci/test.sh
    - stage: Test Pull
      env: TAG=alpine-3.5
      script:
        - ./sh/ci/test.sh
