dist: trusty
git:
  depth: 1
language: node_js
sudo: required


before_install:
  - ./docker-util/sh/update-docker-on-travis.sh
  - sudo service docker stop
  - sudo dockerd --experimental &
  - docker version

env:
  global:
    - DOCKER_IMAGE_NAME=travis-cli
    - DOCKER_ORGANIZATION=beeglercorp
    - DOCKER_TAG=$DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME

install: true

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - docker build --tag $DOCKER_TAG --compress --force-rm --squash .
        - ./docker-util/sh/test-image-size.sh -i $DOCKER_TAG -t 35
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
            docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
            docker push $DOCKER_TAG;
          fi
